Asp.NETMVCCRUD/Asp.NETMVCCRUD/Controllers/CategoriasController.cs
using Asp.NETMVCCRUD.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Asp.NETMVCCRUD.Controllers
{
    public class CategoriasController : Controller
    {
        DBModel db = new DBModel();
        
        // GET: Categorias
        public ActionResult Index()
        {
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
            return View();
        }

        public ActionResult GetData()
        {
            using (DBModel db = new DBModel())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<Category> empList = db.Categories.ToList<Category>();
                return Json(new { data = empList }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            db.Configuration.LazyLoadingEnabled = false;
            if (id == 0)
                return View(new Category());
            else
            {
                using (DBModel db = new DBModel())
                {
                    db.Configuration.LazyLoadingEnabled = false;
                    return View(db.Categories.Where(x => x.CategoryID == id).FirstOrDefault<Category>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Category cat)
        {
            using (DBModel db = new DBModel())
            {
                db.Configuration.LazyLoadingEnabled = false;
                if (cat.CategoryID == 0)
                {
                    cat.FecIns = DateTime.Now;
                    cat.Active = true;
                    db.Categories.Add(cat);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    cat.FecUpd = DateTime.Now;
                    db.Entry(cat).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            
            using (DBModel db = new DBModel())
            {
                db.Configuration.LazyLoadingEnabled = false;//ver despues de terminar si es q lo hago ctm
                Category cat= db.Categories.Where(x => x.CategoryID== id).FirstOrDefault<Category>();
                cat.Active = false;
                db.Categories.Remove(cat);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Asp.NETMVCCRUD/Asp.NETMVCCRUD/Controllers/ProveedoresController.cs
using Asp.NETMVCCRUD.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace Asp.NETMVCCRUD.Controllers
{
    public class ProveedoresController : Controller
    {
        DBModel db = new DBModel();

        // GET: Proveedores
        public ActionResult Index()
        {
            db.Configuration.LazyLoadingEnabled = false;
            db.Configuration.ProxyCreationEnabled = false;
            return View();
        }

        public ActionResult GetData()
        {
            using (DBModel db = new DBModel())
            {
                db.Configuration.LazyLoadingEnabled = false;
                List<Supplier> empList = db.Suppliers.ToList<Supplier>();
                return Json(new { data = empList }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            db.Configuration.LazyLoadingEnabled = false;
            if (id == 0)

                return View(new Supplier());
            else
            {
                using (DBModel db = new DBModel())
                {
                    db.Configuration.LazyLoadingEnabled = false;
                    return View(db.Suppliers.Where(x => x.SupplierID == id).FirstOrDefault<Supplier>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Supplier sup)
        {

            using (DBModel db = new DBModel())
            {
                db.Configuration.LazyLoadingEnabled = false;
                if (sup.SupplierID== 0)
                {
                    sup.FecIns = DateTime.Now;
                    sup.Active = true;
                    db.Suppliers.Add(sup);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    sup.FecUpd= DateTime.Now;
                    
                    db.Entry(sup).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        [HttpPost]
        public ActionResult Delete(int id)
        {

            using (DBModel db = new DBModel())
            {

                db.Configuration.LazyLoadingEnabled = false;//ver despues de terminar si es q lo hago ctm
                Supplier sup = db.Suppliers.Where(x => x.SupplierID == id).FirstOrDefault<Supplier>();
                db.Suppliers.Remove(sup);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Asp.NETMVCCRUD/Asp.NETMVCCRUD/Views/Proveedores/AddOrEdit.cshtml
@model  Asp.NETMVCCRUD.Models.Supplier
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Proveedores", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.SupplierID)
    <div class="form-group">
        <div class="container">
            <div class="col-md-3 ">

                @Html.Label("Nombre de Compañía", new { @class = "control-label "})
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control alphaonly ", maxlength = 20 } })
                @Html.ValidationMessageFor(model => model.CompanyName)
            </div>
            <div class="col-md-3 ">
                @Html.Label("Nombre de Contacto", new { @class = "control-label" })
                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control alphaonly", maxlength = 20 } })
                @Html.ValidationMessageFor(model => model.ContactName)
            </div>
        </div>

        <div class="container">
            <div class="col-md-3 ">

                @Html.Label("Título de Contacto", new { @class = "control-label" })
                @Html.EditorFor(model => model.ContactTitle, new { htmlAttributes = new { @class = "form-control alphaonly", maxlength = 20 } })
                @Html.ValidationMessageFor(model => model.ContactTitle)
            </div>
            <div class="col-md-3 ">
                @Html.Label("Ciudad", new { @class = "control-label" })
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control alphaonly", maxlength = 15 } })
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>
        <div class="container">
            <div class="col-md-3 ">
                @Html.Label("Teléfono", new { @class = "control-label" })
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @type = "number", maxlength = 13 } })
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>
        <div class="container">
            <div class="col-md-6 ">

                @Html.Label("Dirección", new { @class = "control-label" })
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control ", maxlength = 55 } })
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="container">
            <div class="col-md-6">
                <input type="submit" value="Ingresar" class="btn btn-primary" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
        <script>
            $(document).ready(function () {
                $('.alphaonly').bind('keyup blur', function () {
                    var node = $(this);
                    node.val(node.val().replace(/[^a-z]/g, ''));
                }
                );
            });
        </script>

        }

Asp.NETMVCCRUD/Asp.NETMVCCRUD/Views/Proveedores/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<br />
<br />
<br />
<h2>Proveedores</h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Proveedores")')"><i class="fa fa-plus"></i> Add New</a>
<table id="SupplierTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Compañia</th>
            <th>Contacto</th>
            <th>Titulo de contacto</th>
            <th>Direccion</th>
            <th>Ciudad</th>
            @*<th>Region</th>
                    <th>Codigo postal</th>
                <th>Pais</th>*@
            <th>Telefono</th>
            @*<th>Fax</th>
                <th>Pagina Web</th>*@

            <th></th>
        </tr>
    </thead>
</table>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

@section scripts{

    <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>





                var Popup, dataTable;
                $.fn.dataTable.ext.errMode = function (settings, helpPage, message) {
                    console.log("mensaje error "+ message);
                };

                $(document).ready(function () {

                    dataTable = $("#SupplierTable").DataTable({
                        "ajax": {
                            "url": "/Proveedores/GetData",
                            "type": "GET",
                            "datatype": "json"
                        },


                        "columns": [
                            { "data": "CompanyName" },
                            { "data": "ContactName" },
                            { "data": "ContactTitle" },
                            { "data": "Address" },
                            { "data": "City" },
                            //{ "data": "Region" },
                            //{ "data": "PostalCode" },
                            //{ "data": "Country" },
                            { "data": "Phone" },
                            //{ "data": "Fax" },
                            //{ "data": "HomePage" },
                            {
                                "data":"SupplierID" , "render" : function (data) {
                                return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Proveedores")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> Delete</a>";
                            },
                                "orderable": false,
                                "searchable":false,
                                "width":"150px"
                            }

                        ],
                        "language": {
                            "emptyTable" : "No se encontraron datos, porfavor haga click en<b>Add New</b> Button"
                        }
                    });
                }

                );

                function PopupForm(url) {
                    var formDiv = $('<div/>');
                    $.get(url)
                    .done(function (response) {
                        formDiv.html(response);

                        Popup = formDiv.dialog({
                            autoOpen: true,
                            resizable: false,
                            title: 'LLenar detalles de Proveedor',
                            height: 500,
                            width: 700,
                            close: function () {
                                Popup.dialog('destroy').remove();
                            }

                        });
                    });
                }

                function SubmitForm(form) {
                    $.validator.unobtrusive.parse(form);
                    if($(form).valid()){
                        $.ajax({
                            type : "POST",
                            url : form.action,
                            data : $(form).serialize(),
                            success : function (data) {
                                if(data.success)
                                {
                                    Popup.dialog('close');
                                    dataTable.ajax.reload();

                                    $.notify(data.message,{
                                        globalPosition :"top center",
                                        className : "success"
                                    })

                                }
                            }
                        });
                    }
                    return false;
                }

        function Delete(id) {
            swal.fire({
                title: "Esta seguro?",
                text: "No podra recuperar este dato!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Si, eliminarlo!",
                closeOnConfirm: false
            }, function (isConfirm) {
                console.log("isconfirm " + isConfirm)
                if (!isConfirm) return;
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Proveedores")/' + id,
                    success: function (data) {
                        if (data.success) {
                            swal("Hecho!", "Su registro ha sido eliminado correctamente!", "Exito");
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        swal("Error al borrar!", "Porfavor intente mas tarde", "error");
                    }

                });
            });
        }


          //este es original ver si funca anterior pa borrar esta wea fea
        @*function Delete(id) {
            if(confirm('Esta seguro que desea eliminar esta categoria, se eliminaran los asociados ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Categorias")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }*@




    </script>
}